### ISSUE TITLE
small bug

### ISSUE THREAD

**Issue by ashenkirana217** [Bluexin/mcui#19]
so i downloaded the 1.12.2-2.0.9 ui mod and noticed that i cant access the crafting menu through the ui and the bubbles that hover around the player are not there. i didnt know if y'all are aware of this so i thought i would let y'all know
![Screenshot (3)](https://user-images.githubusercontent.com/29134357/71539834-80bf1780-28ff-11ea-8ae1-b780967638bb.png)
![Screenshot (4)](https://user-images.githubusercontent.com/29134357/71539835-8157ae00-28ff-11ea-86e7-e5375294406e.png)
![Screenshot (5)](https://user-images.githubusercontent.com/29134357/71539836-8157ae00-28ff-11ea-8431-a2139f867e8b.png)

**Comment by Tencao** [comment]
This is still in beta as the entire backend of the mod has been rewritten, thus those features are not yet in.

**Comment by ashenkirana217** [comment]
Roger that. I look forward to seeing this mod blossom.
