### ISSUE TITLE
Game crashes when I'm on fire

### ISSUE THREAD

**Issue by CliffyyMantis183** [Bluexin/mcui#32]
I'm playing Minecraft with this mod and when I touch the fire, the game crashes and the world is lost because I'm always in the fire.
[latestlog (3).txt](https://github.com/user-attachments/files/17270204/latestlog.3.txt)
Here's the crash log
I just need some help :(

**Comment by Tencao** [comment]
I'm not sure entirely what has caused this, but as the system that caused this crash has been significantly reworked in dev, we have to assume the bug is fixed there and just ask that you wait for the next beta release and try again.
